export const OrderStatusEnum = {
  ORDER_PLACED: 'ORDER_PLACED',
  WAITING_FOR_CONFIRMATION: 'WAITING_FOR_CONFIRMATION',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_STARTED: 'ORDER_STARTED',
  JOB_STARTED: 'JOB_STARTED',
  JOB_ENDED: 'JOB_ENDED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  WAITING_FOR_PAYMENT: 'WAITING_FOR_PAYMENT',
  PAYMENT_SUCCESSFUL: 'PAYMENT_SUCCESSFUL',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_REJECTED: 'ORDER_REJECTED'
};
